import XCTest
@testable import Qtunnel

final class RC4CipherTests: XCTestCase {

    func test_encryptDecryptRoundtrip() {
        let cipher = CipherFactory.make(method: .rc4, secret: "testsecret")
        let plain: [UInt8] = Array("thisISaCLEARtext".utf8)
        var ciphered = plain
        cipher.encrypt(&ciphered)
        XCTAssertNotEqual(ciphered, plain, "密文 != 明文")
        cipher.decrypt(&ciphered)
        XCTAssertEqual(ciphered, plain, "解密回明文")
    }

    func test_longStreamDoesNotLeakKey() {
        let cipher = CipherFactory.make(method: .rc4, secret: "longstreamkey")
        let plain = [UInt8](repeating: 0xAB, count: 1_000_000)
        var ciphered = plain
        cipher.encrypt(&ciphered)
        // 全部相等才能解密
        cipher.decrypt(&ciphered)
        XCTAssertEqual(ciphered, plain)
    }

    func test_GoServerTestVector() {
        // 模拟 Go cipher_test.go::TestRC4
        let secret = "testsecret"
        let clearText = "thisISaCLEARtext"
        let cipher = CipherFactory.make(method: .rc4, secret: secret)
        var dst = [UInt8](clearText.utf8)
        cipher.encrypt(&dst)
        var dst2 = dst
        cipher.decrypt(&dst2)
        XCTAssertEqual(String(bytes: dst2, encoding: .utf8), clearText)
    }

    func test_encryptMatchesGoOutput() {
        // Cross-implementation interop test vector
        // Generated by Go with same key derivation + RC4:
        //   key := secretToKey("testsecret", 16)
        //   cipher := rc4.NewCipher(key)
        //   cipher.XORKeyStream(ciphertext, plaintext)
        // where plaintext = "GET / HTTP/1.0\r\nHost: 127.0.0.1\r\n\r\n"
        // expected ciphertext = f68b705420c34b80b4cf40d03f2e090e1042ba3f9dae210a2b81fd29691b23e07cba41
        let secret = "testsecret"
        let plaintext = "GET / HTTP/1.0\r\nHost: 127.0.0.1\r\n\r\n"
        let expectedHex = "f68b705420c34b80b4cf40d03f2e090e1042ba3f9dae210a2b81fd29691b23e07cba41"

        let cipher = CipherFactory.make(method: .rc4, secret: secret)
        var ciphertext = [UInt8](plaintext.utf8)
        cipher.encrypt(&ciphertext)

        let actualHex = ciphertext.map { String(format: "%02x", $0) }.joined()
        XCTAssertEqual(actualHex, expectedHex, "Swift RC4 output must match Go RC4 output byte-for-byte")
    }

    func test_decryptMatchesGoOutput() {
        // Inverse: given ciphertext from Go, Swift should decrypt to the original plaintext
        let secret = "testsecret"
        let expectedPlaintext = "GET / HTTP/1.0\r\nHost: 127.0.0.1\r\n\r\n"
        let ciphertextHex = "f68b705420c34b80b4cf40d03f2e090e1042ba3f9dae210a2b81fd29691b23e07cba41"

        var ciphertext: [UInt8] = []
        var idx = ciphertextHex.startIndex
        while idx < ciphertextHex.endIndex {
            let next = ciphertextHex.index(idx, offsetBy: 2, limitedBy: ciphertextHex.endIndex) ?? ciphertextHex.endIndex
            if let byte = UInt8(ciphertextHex[idx..<next], radix: 16) {
                ciphertext.append(byte)
            }
            idx = next
        }

        let cipher = CipherFactory.make(method: .rc4, secret: secret)
        var plaintext = ciphertext
        cipher.decrypt(&plaintext)

        XCTAssertEqual(String(bytes: plaintext, encoding: .utf8), expectedPlaintext)
    }
}
